blueprint:
  name: "Gemini Morning Health Coach & Image Generator"
  description: |
    ## 🤖 Gemini AI Morning Health Coach
    
    **Turn your Garmin stats into a personalized AI morning briefing.**
    
    ### ⚠️ Prerequisites
    1.  **Python Script:** Place `gemini_image.py` in your `/config` folder.
    2.  **Helper:** Create a **Text Helper** (Settings > Devices > Helpers > Create Helper > Text) named `Morning Report`.
    3.  **Shell Command:** Add `generate_gemini_image` to `configuration.yaml`.
    
    [View Setup Guide](https://github.com/bradooken/ha-gemini-coach)

  domain: automation
  input:
    gemini_api_key:
      name: Google Gemini API Key
      selector:
        text:
          type: password
    notification_style:
      name: Notification Style
      description: "Choose 'Mobile App' for a quick push or 'Email' for the full HTML report."
      selector:
        select:
          options:
            - Mobile App
            - Email
          mode: dropdown
      default: Mobile App
    notify_device:
      name: Mobile Device (App Notification)
      description: Required if Style is 'Mobile App'.
      default: ""
      selector:
        device:
          integration: mobile_app
          multiple: false
    email_service:
      name: Email Service (Email Notification)
      description: Required if Style is 'Email' (e.g., notify.gmail).
      default: notify.gmail
      selector:
        text:
    report_helper:
      name: Report Text Helper
      description: Select the Text helper used to store the report for your dashboard.
      selector:
        entity:
          domain: input_text
    dashboard_path:
      name: Dashboard Path
      default: "/health-report"
      selector:
        text:
    sport_focus:
      name: Sport Focus
      selector:
        select:
          options: [Triathlon, Running, Cycling, Swimming, Yoga, General Fitness]
          mode: dropdown
    sleep_sensor:
      name: Sleep Score Sensor
      selector:
        entity:
          domain: sensor
    body_battery_sensor:
      name: Body Battery Sensor
      selector:
        entity:
          domain: sensor
    alarm_sensor:
      name: Next Alarm Sensor
      selector:
        entity:
          domain: sensor
          device_class: timestamp

variables:
  sleep_sensor: !input sleep_sensor
  body_battery_sensor: !input body_battery_sensor
  alarm_sensor: !input alarm_sensor
  sport_focus: !input sport_focus
  report_helper: !input report_helper
  notification_style: !input notification_style
  dashboard_path: !input dashboard_path

trigger:
  - platform: template
    value_template: >-
      {% set alarm = states(alarm_sensor) %} 
      {% if alarm not in ['unavailable', 'unknown'] %}
        {{ now() >= as_datetime(alarm) + timedelta(minutes=5) }}
      {% else %}
        false
      {% endif %}

condition:
  - condition: template
    value_template: >-
      {{ this.attributes.last_triggered == None or 
         this.attributes.last_triggered.date() != now().date() }}

action:
  - variables:
      api_key: !input gemini_api_key
      sleep_val: "{{ states(sleep_sensor) | int(default=60) }}"
      energy_val: "{{ states(body_battery_sensor) | int(default=50) }}"
      focus_mode: "{{ sport_focus }}"
      style: "{{ notification_style }}"
      
      final_prompt: "A {{ focus_mode }} scene. Biometrics: Sleep {{ sleep_val }}, Energy {{ energy_val }}."

  - service: shell_command.generate_gemini_image
    data:
      prompt: "{{ final_prompt }}"
      api_key: "{{ api_key }}"

  # We use a sequence here so the variable is available to the setter
  - service: conversation.process
    data:
      agent_id: conversation.google_ai_conversation
      text: >
        You are an elite Coach. Review these metrics: Sleep: {{ sleep_val }}/100, Energy: {{ energy_val }}/100. 
        Provide a recovery assessment and one tip for {{ focus_mode }}. Under 60 words.
    response_variable: gemini_response

  # Save the report to the Helper IMMEDIATELY after getting the response
  - service: input_text.set_value
    target:
      entity_id: !input report_helper
    data:
      value: "{{ gemini_response.response.speech.plain.speech }}"

  # Now handle notifications
  - choose:
      - conditions: "{{ style == 'Mobile App' }}"
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "☀️ Health Report Ready"
            message: "Your AI coach has reviewed your metrics. Tap to view your briefing."
            data:
              image: "/local/daily_briefing_img.jpg?t={{ now().timestamp() | int }}"
              clickAction: "{{ dashboard_path }}"
      
      - conditions: "{{ style == 'Email' }}"
        sequence:
          - service: !input email_service
            data:
              title: "💪 Morning Report: {{ focus_mode }}"
              message: HTML required.
              data:
                images:
                  - /config/www/daily_briefing_img.jpg
                html: |
                  <!DOCTYPE html> <html> <body>
                    <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
                      <img src="cid:daily_briefing_img.jpg" style="width: 100%; border-radius: 12px;">
                      <h2 style="text-align:center;">☀️ {{ now().strftime('%A, %d %B') }}</h2>
                      <div style="background:#f4f4f4; padding:15px; border-radius:8px; margin:15px 0;">
                        <p><strong>Sleep:</strong> {{ sleep_val }} | <strong>Energy:</strong> {{ energy_val }}</p>
                        <p><em>{{ gemini_response.response.speech.plain.speech }}</em></p>
                      </div>
                    </div>
                  </body> </html>
