blueprint:
  name: "Gemini Morning Health Coach & Image Generator"
  description: |
    ## 🤖 Gemini AI Morning Health Coach
    
    **Turn your Garmin stats into a personalized AI morning briefing.**
    
    This blueprint uses **Google Gemini** (for coaching tips) and **Imagen 3** (for visuals) to generate a unique report based on your Sleep & Body Battery scores.
    
    ### ✨ Key Features
    * 🎨 **Dynamic Visuals:** Generates a custom 16:9 image based on your "Vibe" (Energy levels) and Sport.
    * 🏃‍♂️ **AI Coaching:** Provides a specific, technical training tip based on your recovery metrics.
    * 📱 **Dual Mode:** Choose between a rich **HTML Email** or a **Mobile App** push notification.
    
    ---
    
    ### ⚠️ Critical Setup Steps
    **This blueprint requires manual setup to work.**
    
    1.  **Download Script:** You must place `gemini_image.py` in your `/config` folder.
    2.  **Edit Config:** Add the following line to `configuration.yaml` and restart HA:
    
    ```yaml
    shell_command:
      generate_gemini_image: 'python3 /config/gemini_image.py "{{ prompt }}" "{{ api_key }}"'
    ```
    
    3.  **Google Cloud:** Your API Key must have the **Vertex AI API** enabled (Search "Vertex AI" in Google Cloud Console -> Enable).
    
    [View Full Documentation & Support](https://github.com/bradooken/ha-gemini-coach)

  domain: automation
  input:
    gemini_api_key:
      name: Google Gemini API Key
      description: Your API Key from Google Cloud (must have Vertex AI enabled).
      selector:
        text:
          type: password
    notification_style:
      name: Notification Style
      description: Choose how you want to receive the briefing.
      selector:
        select:
          options:
            - Mobile App
            - Email
          mode: dropdown
      default: Mobile App
    notify_device:
      name: Mobile Device (App Notification)
      description: Required if Style is 'Mobile App'. Select the device to receive the notification.
      default: ""
      selector:
        device:
          integration: mobile_app
          multiple: false
    email_service:
      name: Email Service (Email Notification)
      description: Required if Style is 'Email'. The service to use (e.g., notify.gmail).
      default: notify.gmail
      selector:
        text:
    sport_focus:
      name: Sport Focus
      description: Choose your primary sport for the coaching tip and image subject.
      selector:
        select:
          options:
            - Triathlon
            - Running
            - Cycling
            - Swimming
            - General Fitness
            - Yoga
          mode: dropdown
    sleep_sensor:
      name: Sleep Score Sensor
      description: Your Sleep Score sensor (0-100).
      selector:
        entity:
          domain: sensor
    body_battery_sensor:
      name: Body Battery / Energy Sensor
      description: Your Body Battery or Recovery Score sensor (0-100).
      selector:
        entity:
          domain: sensor
    alarm_sensor:
      name: Next Alarm Sensor (Trigger)
      description: The automation will run 5 minutes after this alarm goes off.
      selector:
        entity:
          domain: sensor
          device_class: timestamp

variables:
  # Map inputs to variables so they can be used in templates
  sleep_sensor: !input sleep_sensor
  body_battery_sensor: !input body_battery_sensor
  alarm_sensor: !input alarm_sensor
  sport_focus: !input sport_focus
  notification_style: !input notification_style

trigger:
  - platform: template
    value_template: >-
      {% set alarm = states(alarm_sensor) %} 
      {% if alarm not in ['unavailable', 'unknown'] %}
        {{ now() >= as_datetime(alarm) + timedelta(minutes=5) }}
      {% else %}
        false
      {% endif %}

condition:
  - condition: template
    value_template: >-
      {{ this.attributes.last_triggered == None or 
         this.attributes.last_triggered.date() != now().date() }}

action:
  - variables:
      api_key: !input gemini_api_key
      style: "{{ notification_style }}"
      sleep_val: "{{ states(sleep_sensor) | int(default=60) }}"
      energy_val: "{{ states(body_battery_sensor) | int(default=50) }}"
      focus_mode: "{{ sport_focus }}"
      
      mood_prompt: >-
        {% if sleep_val > 80 and energy_val > 80 %}
          energetic, vibrant, triumphant atmosphere, golden hour lighting, feeling of peak performance, highly detailed.
        {% elif sleep_val < 55 or energy_val < 40 %}
          moody, atmospheric, overcast, dramatic cinematic lighting, grit and determination, storm clouds.
        {% else %}
          calm, balanced, steady, clear daylight, professional photography style, soft focus.
        {% endif %}
      
      activity_prompt: >-
        {% if focus_mode == 'Triathlon' %}
          A triathlete running towards a bicycle in a transition area, wearing a professional triathlon suit.
        {% elif focus_mode == 'Running' %}
          A runner on a scenic mountain trail ridge.
        {% elif focus_mode == 'Swimming' %}
          A swimmer breaking the surface of the water, water droplets in air.
        {% elif focus_mode == 'Cycling' %}
          A road cyclist climbing a steep winding road.
        {% elif focus_mode == 'Yoga' %}
          A person practicing yoga in a serene studio with natural light.
        {% else %}
          A person stretching in a modern, peaceful studio with large windows.
        {% endif %}
      
      final_prompt: >-
        {{ (activity_prompt ~ " " ~ mood_prompt) | replace('\n', ' ') | replace('"', '') | trim }}

  - service: shell_command.generate_gemini_image
    data:
      prompt: "{{ final_prompt }}"
      api_key: "{{ api_key }}"

  - parallel:
      - delay: "00:00:15"
      - service: conversation.process
        data:
          agent_id: conversation.google_ai_conversation
          text: >
            You are an elite Coach. Review these daily metrics:
            - Sleep: {{ sleep_val }}/100 
            - Energy: {{ energy_val }}/100 
            
            Provide a brief recovery assessment and one specific tip for {{ focus_mode }}.
            Keep it under 60 words. Be motivating but realistic.
        response_variable: gemini_response

  - choose:
      - conditions: "{{ style == 'Mobile App' }}"
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "☀️ Morning Brief: {{ focus_mode }}"
            message: "{{ gemini_response.response.speech.plain.speech }}\n\n💤 Sleep: {{ sleep_val }} | 🔋 Energy: {{ energy_val }}"
            data:
              image: "/local/daily_briefing_img.jpg?t={{ now().timestamp() | int }}"
              clickAction: "/lovelace/home"
      
      - conditions: "{{ style == 'Email' }}"
        sequence:
          - service: !input email_service
            data:
              title: "💪 Morning Report: {{ focus_mode }}"
              message: HTML required.
              data:
                images:
                  - /config/www/daily_briefing_img.jpg
                html: |
                  <!DOCTYPE html> <html> <body>
                    <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
                      <img src="cid:daily_briefing_img.jpg" style="width: 100%; border-radius: 12px;">
                      <h2 style="text-align:center;">☀️ {{ now().strftime('%A, %d %B') }}</h2>
                      <div style="background:#f4f4f4; padding:15px; border-radius:8px; margin:15px 0;">
                        <p><strong>Sleep:</strong> {{ sleep_val }} | <strong>Energy:</strong> {{ energy_val }}</p>
                        <p><em>{{ gemini_response.response.speech.plain.speech }}</em></p>
                      </div>
                    </div>
                  </body> </html>
